### ISSUE TITLE
Need to remove extraneous fetch during verify_pr now that refspec includes refs/pull-requests/*

### ISSUE THREAD

**Issue by terabyte** [terabyte/stashbot#26]
Title says it all.  issue #19 was solved by PR#23 so the refs are available without fetch, but we have to stop actually doing the fetch because it will fail in the case were the PR is from a fork into a parent repo and the stashbot user does not have read permission on the forked repo.

Workaround is to make stashbot user a system admin so it can read everything.

**Comment by memory** [comment]
Actually PR23 only added the refspec to the _verify_ build.  If we want it in the verify_pr build we'll need to add that.

**Comment by terabyte** [comment]
the fetch was causing problems, so we removed it as part of PR #35 / #28 - so this is done now
